@extends('client.master')

@section('content')
    <!-- Hero Section with 3D Carousel -->
    <section class="hero" id="home">
        <div class="carousel-container">
            <div class="carousel" id="carousel">
                <!-- Carousel items will be generated by JavaScript -->
            </div>

            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>

            <div class="carousel-indicators" id="indicators">
                <!-- Indicators will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- NEW: Prism Philosophy Section (About) -->
    <section class="philosophy-section" id="about">
        <div class="philosophy-container">
            <div class="prism-line"></div>

            <h2 class="philosophy-headline">
                Masjid Al-...<br>Deskripsi
            </h2>

            <p class="philosophy-subheading">
                At PRISM FLUX, we transform complex challenges into elegant solutions through the convergence of
                cutting-edge technology and visionary design. Every project is a spectrum of possibilities
                waiting to be discovered.
            </p>

            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">💎</div>
                    <h3 class="pillar-title">Innovation</h3>
                    <p class="pillar-description">
                        Breaking boundaries with revolutionary approaches that redefine industry standards and push the
                        limits of what's possible. Elevate your designs with premium vector stickers from <a
                            href="https://www.vectorsticker.com" rel="nofollow" target="_blank">VectorSticker</a>.
                    </p>
                </div>

                <div class="pillar">
                    <div class="pillar-icon">🔬</div>
                    <h3 class="pillar-title">Precision</h3>
                    <p class="pillar-description">
                        Meticulous attention to detail ensures every pixel, every line of code, and every interaction is
                        perfectly crafted by <a href="https://templatemo.com" rel="nofollow" target="_blank"
                            style="color: var(--accent-cyan); text-decoration: none;">TemplateMo</a>, enhanced with
                        stunning visuals from <a href="https://unsplash.com" rel="nofollow" target="_blank"
                            style="color: var(--accent-cyan); text-decoration: none;">Unsplash</a>.
                    </p>
                </div>

                <div class="pillar">
                    <div class="pillar-icon">∞</div>
                    <h3 class="pillar-title">Evolution</h3>
                    <p class="pillar-description">
                        Continuous adaptation and growth, staying ahead of trends while building timeless solutions for
                        tomorrow. Boost your productivity with the easy-to-use timer tools at <a href="https://timermo.com"
                            rel="nofollow" target="_blank">TimerMo</a>.
                    </p>
                </div>
            </div>

            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Stats Section with Content -->
    <section class="stats-section" id="stats">
        <div class="section-header">
            <h2 class="section-title">Artikel Masjid</h2>
            <p class="section-subtitle">Real-time analytics and achievements powered by cutting-edge technology</p>
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon">🚀</div>
                <div class="stat-number" data-target="150">0</div>
                <div class="stat-label">Projects Completed</div>
                <p class="stat-description">Successfully delivered enterprise-level solutions across multiple industries
                    with 100% on-time completion rate.</p>
            </div>

            <div class="stat-card">
                <div class="stat-icon">⚡</div>
                <div class="stat-number" data-target="99">0</div>
                <div class="stat-label">Client Satisfaction %</div>
                <p class="stat-description">Maintaining excellence through continuous feedback loops and agile
                    development methodologies.</p>
            </div>

            <div class="stat-card">
                <div class="stat-icon">🏆</div>
                <div class="stat-number" data-target="25">0</div>
                <div class="stat-label">Industry Awards</div>
                <p class="stat-description">Recognized globally for innovation in digital transformation and
                    technological advancement.</p>
            </div>

            <div class="stat-card">
                <div class="stat-icon">💎</div>
                <div class="stat-number" data-target="500">0</div>
                <div class="stat-label">Code Commits Daily</div>
                <p class="stat-description">Continuous integration and deployment with automated testing ensuring
                    maximum code quality.</p>
            </div>
        </div>
    </section>

    <section class="stats-section" id="stats">
        <div class="section-header">
            <h2 class="section-title">Infaq</h2>
            <p class="section-subtitle">Real-time analytics and achievements powered by cutting-edge technology</p>
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon">🚀</div>
                <div class="stat-number" data-target="150">0</div>
                <div class="stat-label">Projects Completed</div>
                <p class="stat-description">Successfully delivered enterprise-level solutions across multiple industries
                    with 100% on-time completion rate.</p>
            </div>
        </div>
    </section>

    <!-- Enhanced Skills Section - Technical Arsenal -->
    <section class="skills-section" id="skills">
        <div class="skills-container">
            <div class="section-header">
                <h2 class="section-title">Galeri Masjid</h2>
                <p class="section-subtitle">Mastery of cutting-edge technologies and frameworks</p>
            </div>

            <div class="skill-categories">
                <div class="category-tab active" data-category="all">All Skills</div>
                <div class="category-tab" data-category="frontend">Frontend</div>
                <div class="category-tab" data-category="backend">Backend</div>
                <div class="category-tab" data-category="cloud">Cloud & DevOps</div>
                <div class="category-tab" data-category="emerging">Emerging Tech</div>
            </div>

            <div class="skills-hexagon-grid" id="skillsGrid">
                <!-- Hexagonal skill items will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section class="contact-section" id="contact">
        <div class="section-header">
            <h2 class="section-title">Initialize Connection</h2>
            <p class="section-subtitle">Ready to transform your vision into reality? Let's connect.</p>
        </div>

        <div class="contact-container">
            <div class="contact-info">
                <a href="https://maps.google.com/?q=Silicon+Valley+CA+94025" target="_blank" class="info-item">
                    <div class="info-icon">📍</div>
                    <div class="info-text">
                        <h4>Location</h4>
                        <p>Silicon Valley, CA 94025</p>
                    </div>
                </a>

                <a href="mailto:hello@prismflux.io" class="info-item">
                    <div class="info-icon">📧</div>
                    <div class="info-text">
                        <h4>Email</h4>
                        <p>hello@prismflux.io</p>
                    </div>
                </a>

                <a href="tel:+15551234567" class="info-item">
                    <div class="info-icon">📱</div>
                    <div class="info-text">
                        <h4>Phone</h4>
                        <p>+1 (555) 123-4567</p>
                    </div>
                </a>

                <a href="https://calendly.com" target="_blank" class="info-item">
                    <div class="info-icon">📅</div>
                    <div class="info-text">
                        <h4>Schedule Meeting</h4>
                        <p>Book a consultation</p>
                    </div>
                </a>
            </div>

            <form class="contact-form" id="contactForm">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" required>
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" required>
                </div>

                <div class="form-group">
                    <label for="subject">Subject</label>
                    <input type="text" id="subject" name="subject" required>
                </div>

                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea id="message" name="message" required></textarea>
                </div>

                <button type="submit" class="submit-btn">Transmit Message</button>
            </form>
        </div>
    </section>
@endsection
